import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "@/styles/globals.css";
import Header from '@/layouts/Header';

const roboto = Roboto({ subsets: ["latin"],weight:["400","500","700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Header />
        <main className='mt-[64px] flex flex-1 flex-col'>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
